#imports
include ./theme.conf

# Basic config 
kitty_mod ctrl+shift
enable_audio_bell no
shell zsh

# Fonts
font_family      JetBrainsMono Nerd Font
bold_font        JetBrainsMono Nerd Font Bold
italic_font      JetBrainsMono Nerd Font Italic
bold_italic_font JetBrainsMono Nerd Font Bold Italic
font_size 11

# Windows
window_margin_width 2
window_border_width 1pt
single_window_margin_width 0

#Tab bar
tab_bar_style powerline 
tab_powerline_style slanted
tab_bar_edge top 
tab_bar_align left 
active_tab_font_style   bold
inactive_tab_font_style normal
tab_title_template {title}{' :{}:'.format(num_windows) if num_windows > 1 else ''}

# Title Bar
x11_hide_window_decorations True 

# Managing windows and tabs
map F1 launch --cwd=current
map F2 new_tab_with_cwd
map F3 new_tab

# Open current tab in a new OS window (like browser "move tab to new window")
map F5 detach_tab

# Save/load tab layouts (sessions)
# F4 then s = save current layout to resume later
map F4>s save_as_session
# F4 then g = load a saved layout
map F4>g goto_session ./sessions

# Cursor config
shell_integration  no-cursor
cursor_shape block

# Make inactive windows darker
inactive_text_alpha 0.5

# Optional: Highlight the active border
inactive_border_color #333333 
